# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 04:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0002_auto_20171029_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotizacion',
            old_name='cantida',
            new_name='cantidad',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='fecha',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[(b'S', b'Solicitud'), (b'A', b'Aprobado'), (b'R', b'Rechazado')], max_length=1),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cotizacion.Proveedor'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='unidad',
            field=models.CharField(choices=[(b'U', b'Unidad'), (b'M', b'Metro'), (b'L', b'Litro')], max_length=1),
        ),
    ]
