# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 00:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cotizacion', '0003_auto_20171031_2334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'verbose_name_plural': 'Cotizaciones'},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name_plural': 'Personas'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name_plural': 'Proveedores'},
        ),
        migrations.RemoveField(
            model_name='persona',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='nombre',
        ),
        migrations.AddField(
            model_name='persona',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('S', 'Solicitud'), ('A', 'Aprobado'), ('R', 'Rechazado')], max_length=1),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='unidad',
            field=models.CharField(choices=[('U', 'Unidad'), ('M', 'Metro'), ('L', 'Litro')], max_length=1),
        ),
        migrations.AlterField(
            model_name='persona',
            name='cedula',
            field=models.IntegerField(unique=True),
        ),
    ]
