# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 03:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cotizacion', '0004_auto_20171104_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='persona',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
