# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0005_auto_20171105_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='unidad',
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad',
            field=models.CharField(choices=[('U', 'Unidad'), ('M', 'Metro'), ('L', 'Litro')], default='U', max_length=1),
            preserve_default=False,
        ),
    ]
